dna = "TTTCATCAAATTGATCCCGGCCTCCTACGGACGCACTGTTTCACATAATCATGGTCGAGAGGTTATCGACCCGATCCAAAGTTCGCGGTACCCACATTGACTCGTAGTCCGTCATTACACATGTGGGCCTACCTGGACCAGAAAGATCGAACCCGTTATACGGTAGGTAGCTCTTACGCGCGACTATCAACTTCCTAGTAAATTCCACATACAAATTTGAGATAAACCTGAAGCAACGCTGCGTCGTGCAAGCGTCACTCTGCGAACTCAAGGAGCACGTACGGCACATTACGTCTTGTGCAGAAATTGCGTTCACTACTTTTCGAGGGTCATAAACCCGAGCGGAGACCGAACTCGGTGCTAGGAAATGGCAGTCTTATGGGTGCTCTGTCTCTTTACCCAGCGGGACCAAAAGCCCATGGATGCCCCGCTCGACTATTAGCGGTGATCGAGTCCATGGGCGTCCTTACCTGGAGAGGTTTGCACGTTCAACATTTAGGCGACTGGCGCCATTCGGTTAATCTTCGGGGCTTTTCCCTCGGTTAGCGCTCAAAGGGTCTGAATTCTTGGTTCGATTCTAGCTCGAAACCCCACTAGCATCGGATTCAAAGGGAATACTTTTCGCTTGGAAATGGTCTGGGGCACGTACTGGTGTTCGGGCAACTCTGCACTCGGGCATCTTAAGAAATACGTATGTCGCACGTGAATTTATTCCTCGTGCGATACCATCTTTCGGCTTTAGTTATCGGTTATGAAATGACTAAAAGACGTCAGGTTTGATAGAGCGATTTCCTTAGGGAACCATGACCTATTTTCCACTCTGGGCTAGTCTGGAAAAGGGAGGGCTGGAACGAATTGAACGAGGAGAAACCTTCCGACTAGCGACACCCCTTCTTGCGGCAAAACCATATTCCAGGG"

compliment = " "


def coder (dnaA, dnaB) :
    for x in dnaA :
     if x == "T":
        dnaB += "A"
     elif x == "A":
        dnaB += "T"
     elif x == "G":
        dnaB += "C"
     else:
        dnaB += "G"
    return dnaB
 
compliment = coder(dna, compliment)