# Finding a motif in DNA

string = "CCCTTGCCATCCCTTGCTTACAGCTACTGACCCTTGCCCCTTGCCCCCTTGCGGCCCTTGCTCGTGAAGCCCTTGCGCCCTTGCGATGCCCCCCTTGCCCCTTGCCCCTTGCCATTATGGTTTTTACCCTTGCAGGGTCACCCCTTGCTTCCCTTGCTCCCCCTTGCAAGTTCCCCTTGCCCCTTGCCCGCCCTTGCGCGCTCCCCTTGCCCATTTAGCACCCTTGCCCCTTGCTCCCCTTGCCCCTTGCCTACCCTTGCCAACCCTTGCAGCCCTTGCATCCATCGTCTCCCTTGCGACCCTTGCCCCTTGCACGTGCCCTTGCCTGGTACCCCTTGCCCCCTTGCCCCCTTGCCCCTTGCCCCCTTGCGCCCTTGCTCCCTTGCCCCTTGCCCCTTGCCCCTTGCCCCCCTTGCCCGCATTCCCTTGCGCCCTTGCGAGTTACCCTTGCCCCCTTGCCCCTTGCCCCTTGCCTAACCCTTGCGAGCCCTTGCTCCCTTGCGGAGACCCCTTGCCCCTTGCTCCCCCCTTGCCGCCCTTGCCCCCTTGCGTAAACGGACGATCCCTTGCTACACCCTTGCGCCCTTGCATGTATCCCCTTGCTACCACCCCCTTGCGCCCTTGCACTGGGCCCCTTGCATCAACGACTACGCCCCTTGCTTCTAACCCGGTCCCTTGCATCCCTTGCCCCTTGCCCCTTGCGCCCTTGCCCCTTGCCCCTTGCTGCCCTTGCACTAAGCTCCCTTGCCCCTTGCTCCCTTGCATCTAGGCCCTTGCCGGGCCCTTGCGCACTACTCC"

code = "CCCTTGCCC"
locations = []
i = 0

for x in string:
    snippet = string[i: i+9]
    if snippet == code:
        locations.append(i + 1)
    i += 1
    
print locations  #[31, 38, 92, 99, 174, 181, 204, 221, 237, 300, 333, 341, 349, 356, 380, 387, 394, 401, 410, 445, 453, 460, 509, 536, 682, 689, 704, 711, 742]


